name: UtilityCore
main: wockkinmycup\utilitycore\Loader
api: 5.0.0
version: 1.0.1
author: wockkinmycup

permissions:
  utility.admin:
    default: op
  utility.settings:
    default: true
  utility.exp:
    default: true
  utility.exp.see:
    default: op